backend:
  name: github
  repo: reymooy27/portfolio
  branch: master
  base_url: https://reymooy.vercel.app
  auth_endpoint: /api/auth

media_folder: "public"
public_folder: "/"

collections:
  - name: projects
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - {
          label: "Language",
          name: "language",
          widget: "string",
          required: false,
        }
      - {
          label: "Tech Stack",
          name: "techStack",
          widget: "string",
          required: false,
        }
      - {
          label: "GitHub Link",
          name: "githubLink",
          widget: "string",
          required: false,
        }
      - {
          label: "Site Link",
          name: "siteLink",
          widget: "string",
          required: false,
        }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
